export const ACTION_TYPES = {
    FETCH_TASKS: "FETCH_TASKS",
    FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
    FETCH_TASK_FAIL: "FETCH_TASK_FAIL",

    CREATE_TASK: "CREATE_TASK",
    CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
    CREATE_TASK_FAIL: "CREATE_TASK_FAIL",

    UPDATE_TASK: "UPDATE_TASK",
    UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
    UPDATE_TASK_FAIL: "UPDATE_TASK_FAIL",

    DELETE_TASK: "DELETE_TASK",
    DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
    DELETE_TASK_FAIL: "DELETE_TASK_FAIL",

    DRAG_TASK_OPTIMISTIC: "DRAG_TASK_OPTIMISTIC",
    DRAG_TASK_SUCCESS: "DRAG_TASK_SUCCESS",
    DRAG_TASK_FAIL: "DRAG_TASK_FAIL",
}